[package]
name = "uloha"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
dashmap = "7.0.0-rc2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
crossbeam-channel = "0.5.15"

